@echo off
echo Starting SecureGuard IDS Frontend...
cd frontend
echo Installing dependencies with legacy peer deps...
npm install --legacy-peer-deps
echo Starting React development server...
npm start
pause
