@echo off
echo Starting SecureGuard IDS Backend...
cd backend
echo Installing minimal dependencies...
python -m pip install -r requirements-working.txt
echo Starting IDS server...
python main_working.py
pause
